In [1]:
import numpy as np

In [17]:
va = np.array([True, 0, 0, 0], dtype=np.bool)
vb = np.array([0, True, 0, 0], dtype=np.bool)
vc = np.array([0, 0, True, 0], dtype=np.bool)
vd = np.array([0, 0, 0, True], dtype=np.bool)
vz = np.zeros(4)

In [20]:
a = np.array([va + vb + vc, vb, vc, vz])

In [21]:
a

array([[1., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [22]:
x = np.linalg.solve(a, va)

LinAlgError: Singular matrix

In [12]:
x

array([1., 0., 0., 0.])

In [13]:
a*x

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])